name: pesta_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  flutter_map: ^6.1.0        # Library Peta OSM
  latlong2: ^0.9.1           # Objek koordinat
  geocoding: ^3.0.0          # Mencari koordinat dari alamat
  pdf: ^3.10.7      # Tambahkan ini
  printing: ^5.11.1 # Tambahkan ini
  awesome_notifications: ^0.10.1
  shared_preferences: ^2.0.15
  workmanager: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_pln.png
