name: pesta_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geocoding: ^3.0.0
  pdf: ^3.10.7
  printing: ^5.11.1
  shared_preferences: ^2.2.2 # Tambahkan ini untuk session

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true