name: pesta_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  flutter_map: ^6.1.0        # Library Peta OSM
  latlong2: ^0.9.1           # Objek koordinat
  geocoding: ^3.0.0          # Mencari koordinat dari alamat

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
